image: maven:latest
stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean install

test:
  stage: test
  script:
    - mvn verify
    - mvn clean compile test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml